[tool.poetry]
name = "mangaapi"
version = "0.1.0"
description = "A Python-based web scraping API built with FastAPI that provides easy access to manga contents."
authors = ["tokitou-san <tokitousan2005@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.109.0"
uvicorn = {extras = ["standard"], version = "^0.26.0"}
requests = "^2.31.0"
selectolax = "^0.3.17"
pydantic-core = "^2.16.0"
anyio = "^4.2.0"
black = "^23.12.1"
pre-commit = "^3.6.0"
jinja2 = "^3.1.3"
markdown = "^3.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
